### PR TITLE
Added script that extracts all data tables from specified database.

### PR DESCRIPTION
**Pull request by andrewhill157**
This is a script that I use in my overall project that makes use of the macarthur_core/lovd and macarthur_core/web_io to extract data from all data from a given LOVD URL. 

The script makes use of argparse to provide a user interface. The string provided for the command-line interface should hopefully provide an explanation of how it is used. It should save a tab-delimited file for each gene's table data, where each output file is named according to the gene name.

From command line generally it is used in the following way:

```
python extract_data.py --all --leiden_url http://www.dmd.nl/nmdb2/ --output_directory results
```

Users can also print a list of all available genes using:

```
python extract_data.py --genes_available --leiden_url http://www.dmd.nl/nmdb2/
```

### CODE REVIEW

**Comment by zonca** [comment]
This is pretty simple script, not much comments, just for curiosity, how is the output file formatted? is it space-separated?
How big is the output dataset, if you are dumping a full db? Is there a specific reason why you are using text instead of a binary format?

**Comment by andrewhill157** [comment]
The output file is formatted as a tab-delimited text file with one row per line. My reasoning for writing in a non-binary format is that most of these particular databases are not prohibitively large. Most of these files (one per gene) contain few enough entries that I didn't feel the need to compress and at the time it seemed more convinient. There are other datasets we use in the lab that are much much larger and are definitely stored in binary formats!

**Comment by andrewhill157** [comment]
Thank you for all the feedback on this! I addressed the issues you mentioned here as well as two issues from the previous PR (the one I accidentally merged and closed). I will keep this open so I can make the last changes we discussed in that closed PR:
1. Refactoring set_gene_id behavior 
2. Perhaps improving URL handling with urlparse module

**Comment by zonca** [comment]
Better open another PR if you work on those changes, let's use this PR to work on this module

**Comment by zonca** [comment]
Agreed on text format, isn't CSV a little better than tab delimited? What I don't like about tab delimited is that people might mess it up with mix of spaces and tabs.

**Comment by zonca** [comment]
Good you addressed my comments, I think this is good to merge.

**Comment by andrewhill157** [comment]
I tended to use CSV before I started in this lab, but most of the standard file formats we deal with in genomics are tab-delimited. I decided it was best to stick with the convention to be consistent. 

Thanks for the feedback on this module! I will merge this PR and start a new one for the other changes I mentioned.

**Pull request merged**
