### PR TITLE
Added module for remapping variants from HGVS to VCF format.

### PR DESCRIPTION
**Pull request by andrewhill157**
This code contains a new module macarthur_core/remapping. Genetic mutations are often listed in one of two formats, HGVS and VCF. HGVS is compact and has its own (relatively complex) syntax for describing mutations. However, for large scale analysis projects HGVS is extremely difficult to use effectively for a number of reasons. We want to convert data from the Leiden Open Variation Databases (the ones macarthur_core/lovd is designed to interact with) from one format to the other. This is a non-trivial conversion. 

The class VariantRemapper macarthur_core/remapping/remapping.py basically wraps a third party module to make it easier to use within my project. The third party module documentation and description HGVS vs. VCF notation is described here: https://github.com/counsyl/hgvs

Unfortunately, this module depends on two relatively large files that I cannot easily host on github. These are normally housed in a folder called resources within the module. One is a human genome reference sequence (hg19.fa) and the other is a file containing definitions of transcript sequences that are needed to facilitate conversion between the HGVS and VCF (genes.refSeq). If you would like to actually run the code, then we will need get you these files some other way.

### CODE REVIEW

**Comment by zonca** [comment]
About hosting the large files, you could check if you can use the Github `Releases` function.

Also I was thinking that this PR descriptions you are writing would be really helpful to be shipped with the code, they might be useful for other users, why don't you also copy them in `README.md` files in the project?

**Comment by zonca** [comment]
Pretty simple module, nothing to report on this!

**Comment by andrewhill157** [comment]
Thank you again for the feedback! 
- file_io is still missing from the project, I will add it into the project in a future commit
- I'm glad the PR descriptions have been helpful! I will definitely start adding these into a README.md for the whole project.
- From sources I found online previously (https://help.github.com/articles/working-with-large-files, for example), it seemed like GitHub still didn't like hosting large files with them (one of these files is 3.2 GB). Do you think that releases would still work, or would hosting on Dropbox or some other source and providing a link be the best option?

**Comment by zonca** [comment]
3GB! OK, then the best choice is FigSghare, I suggest looking into that

**Comment by zonca** [comment]
Or you can add READMEs in different folders, the good is that github displays that online, so it is very useful for people that are browsing your project there

**Comment by andrewhill157** [comment]
Some of the files we deal with are this size or larger, as there are often on the order of billions of entries associated with the types of data we use in genomics. Luckily, the third-party module uses an indexed search approach, so things in this large file can actually be accessed quite quickly. 

FigShare appears to have a 250 MB file size limit, but say to contact them if you need more space. I will ask my lab-mates if they have any recommendations.

**Comment by zonca** [comment]
I'm sure it is no problem if you contact FigShare, if you show them this file is for general usage.

**Comment by andrewhill157** [comment]
As you suggested here, I have modified the README file to contain the information I have been including with my pull requests along with some additional information. I also connected this project to read the docs and made a build, but the documentation is not complete. I think this may be best handled in a separate PR.

**Comment by andrewhill157** [comment]
I have also hosted zipped versions of the large files at www.broadinstitute.org/~ahill (this is now mentioned in the README). This was something my lab recommended for the code review process. 

These files are derived from files that can be downloaded from standard sources. Because these files might be updated by their hosts with new entries or updates in the future, they thought that In the long-term including instructions on how to download this data along with any scripts that are needed to convert between formats would be a better solution than providing the data itself.

**Comment by andrewhill157** [comment]
Are there any remaining issues that we want to address in this PR?

**Comment by zonca** [comment]
I think the best would be to have both: a prepackaged version for easier use and scripts for reproducibility.
Nothing else on this, good to merge.

**Pull request merged**
